# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

schedules:
- cron: 0 */3 * * * # cron syntax defining a schedule
  displayName: Triggering ReadyAPI tests against VUM services # friendly name given to a specific schedule
  branches:
    include: [ develop ] # which branches the schedule applies to

steps:
- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: '99.6-VUM-API-BRON-Utr-WerkzoekendeProfielen'
    rootFolder: '$(Common.TestResultsDirectory)'