# This pipeline runs ReadyAPI tests agains the VUM services at 03:00 o'clock.

# This pipeline is triggered by time and not by a commit.
trigger: none # Disable CI commit trigger
pr: none # Disable pull request triggers.

pool:
  vmImage: ubuntu-latest

schedules:
- cron: 0 */3 * * * # cron syntax defining a schedule
  displayName: ReadyAPI tests tegen VUM services om 03:00 uur # friendly name given to a specific schedule
  branches:
    include: [ develop ] # which branches the schedule applies to




steps:
- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: '99.6-VUM-API-BRON-Utr-WerkzoekendeProfielen'
    rootFolder: '$(Common.TestResultsDirectory)'
