# Deze pipeline draait ReadyAPI tests tegen de VUM services om 03:00 uur ('s-nachts).

# Trigger obv tijd en niet door een commit.
trigger: none # Zet de CI commit trigger uit
pr: none # Zet de pull request trigger uit.

pool:
  vmImage: ubuntu-latest

schedules:
- cron: 0 */3 * * * # cron syntax tbv een start om 03:00 uur
  displayName: ReadyAPI tests tegen VUM services om 03:00 uur # Display naam van deze schedule
  branches:
    include:
    - develop  # Op welke branch deze schedule van toepassing is

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: https://gitlab.com/inlichtingenbureau/
    userRepository: vum/readyapi_testen_v2
    #defaultVersionType: 'latest' # Opties: latest (=default), specificVersion, specificTag
    #version: # Verplicht als defaultVersionType != Latest
    #itemPattern: '**' # Optioneel file pattern voor te downloaden files
    #downloadPath: '$(System.ArtifactsDirectory)' # Pad op de agent machine waar de release assets worden gedownload
- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: '99.6-VUM-API-BRON-Utr-WerkzoekendeProfielen'
    rootFolder: '$(Common.TestResultsDirectory)'
- task: SendEmail@1
  inputs:
    To: 'odenijs@inlichtingenbureau.nl jgross@inlichtingenbureau'
    From: 'vumtests.inlichtingenbureau.nl'
    Subject: 'Vum test resultaten'
    Body: 'Hier een url naar de test resultaten'
    BodyAsHtml: true
    AddAttachment: false
    SmtpServer: 'smtp.vum.inlichtingenbureau.nl'
    SmtpUsername: 'smtpvum'
  